### ISSUE TITLE
broken transactional patterns

### ISSUE THREAD

**Issue by phraktle** [deephacks/lmdbjni#23]
the following pattern is broken:

        Transaction tx = env.createTransaction();
        try {
            return put(tx, key, value, flags);
        } finally {
            tx.commit();
        }

When put throws an error, the commit still runs. Which causes the commit itself to throw an error, masking the original problem.

**Comment by krisskross** [comment]
When does this happen? Could you provide the error codes for both put and commit?

**Comment by phraktle** [comment]
The put was throwing an "MDB_PAGE_FULL: Internal error - page has no more space" (the reasons are not yet obvious, but that's besides the point. However, the commit clobbered this with a "MDB_BAD_TXN: Transaction cannot recover - it must be aborted", so you couldn't see the underlying error.

**Comment by krisskross** [comment]
Is the commit automatically aborted by LMDB when this happens? Or must it be aborted manually to release the transaction?

**Comment by phraktle** [comment]
I'm not sure if there's a resource leak you don't call abort explicitly, but there's certainly no harm :)

**Comment by krisskross** [comment]
Do you mind adding that to commit() in #24? I.e. call abort before throwing the exception?

**Comment by phraktle** [comment]
With the try-with-resources pattern, that's what actually happens: if the commit failed, the close performs an abort at the end of the block (since self wasn't zeroed by the commit). Doing an abort in commit is confusing.

Plus this pattern takes care of handling any potential [suppressed exceptions](http://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html#suppressed-exceptions).

**Comment by krisskross** [comment]
Yes, but what if you cannot use try-with-resources? Like when using ThreadLocal interceptors for example?

**Comment by phraktle** [comment]
Then the caller has to ensure to close the resource they have opened. Just like for any other resource, e.g. a file handle.

**Comment by krisskross** [comment]
I don't want to beat a dead horse but if the transaction knows that it cannot proceed why not abort right away? Just as a measure to prevent resource leaks. The user can still abort manually and this will be a no-op. 

This a pretty abnormal situation so taking these extra measures might be appropriate?

**Comment by phraktle** [comment]
The reason I'm resisting is that I think it's confusing for the commit API call to implicitly also try an abort. And it also makes proper exception handling there nastier (catch potential the exception from commit, then catch potential exception from abort, add that as a suppressed exception to the first Throwable, etc) – while try-with-resources does all this automatically.

In general, most lmdbjni API users will either do atomic get/put calls, or if they do multiple operations in a transaction, they would use try-with-resources (which is much better than the [pattern proposed by the current lmdbjni driver](https://github.com/phraktle/lmdbjni#usage)).

**Comment by krisskross** [comment]
Alright, let's settle on this approach.

**Comment by phraktle** [comment]
Thanks ;)
