### ISSUE TITLE
db.seek only finding exact matches

### ISSUE THREAD

**Issue by raybellis** [deephacks/lmdbjni#29]
Me again :)

I'm having trouble with `db.seek` only finding exact matches, and not (as per the documentation) "first key greater than or equal to specified key".

I believe the culprit is this, from `EntryIterator.java`:

     public boolean hasNext() {
        if (first) {
          if (key != null) {
            this.entry = cursor.seek(SeekOp.KEY, key);
          }

shouldn't that be `SeekOp.RANGE` rather than `.KEY` ?

**Comment by raybellis** [comment]
FWIW, I've just made this change locally and tested it and am now getting perfect results with my custom comparator :)  Thanks loads for the help!

**Comment by krisskross** [comment]
Great! If you send me a pull request i'll merge it in.
