### ISSUE TITLE
Why not i could get the artifactId that version is 0.4.0 by maven?

### ISSUE THREAD

**Issue by asdf2014** [deephacks/lmdbjni#32]
When i use the following dependecy, i got a problem that could not found the artifactId, but the version is released.

<dependency>
		<groupId>org.deephacks.lmdbjni</groupId>
		<artifactId>lmdbjni-win64</artifactId>
		<version>0.4.0</version>
</dependency>

How can i do to deal with the problem?

**Comment by krisskross** [comment]
My Windows VM is broken and I did not want to go through the problem of building 0.4.0 for Windows if there was no interest for it. 

I'll look into later this week. If you want you can try the 0.3.2 release in the meantime.

```xml
<dependency>
    <groupId>org.deephacks.lmdbjni</groupId>
    <artifactId>lmdbjni-win64</artifactId>
    <version>0.3.2</version>
</dependency>
```

**Comment by krisskross** [comment]
Closing for lack of interest.
