### ISSUE TITLE
Who's using LMDB for Java?

### ISSUE THREAD

**Issue by krisskross** [deephacks/lmdbjni#39]
Add comments on use case and good/bad experience as a user, open source project or company. Description of hardware, operating system, JVM spec, gotchas, opinions and other valuable information are welcome.

**Comment by krisskross** [comment]
No incident in one year of production use on virtualized Ubuntu precise Linux 3.13.0.

1) Queue for storing incoming traffic in protobuf format. A periodic job drains the queue and stores the data in HBase. 
2) Immutable HBase query cache proxy for numeric id to string name lookup.
3) Immutable HBase query cache proxy for historical time series data.

Experience:

- Excellent read and write performance using copy buffers (i.e not zero copy). 
- Sporadic `MDB_BAD_RSLOT: Invalid reuse of reader locktable slot` exceptions was fixed by setting `Constants.NOTLS` option on `Env.open`.
- Development environment on Linux and OSX works well.

**Comment by mauricioscastro** [comment]
starting to use it [here](https://github.com/mauricioscastro/basex-lmdb). so far, so GREAT!, as soon as I have more info and data about the results in terms of performance, practicality, etc I will add them here. for the moment, thanks so much for this.

**Comment by krisskross** [comment]
[RxLMDB](https://github.com/deephacks/RxLMDB) is an open source project that provide a [RxJava](https://github.com/ReactiveX/RxJava) API to lmdbjni.

**Comment by krisskross** [comment]
Moving to Wiki.
