### ISSUE TITLE
New commit cauing exception in Android when Cursor is instantiated

### ISSUE THREAD

**Issue by headuck** [deephacks/lmdbjni#44]
Commit 8f24ae4188af77ec357a513f3096118c2d8ce05f breaks Android builds, since Android cannot use Direct Buffers and the commit causes init of them, causing exception when any cursor is instantiated even though the 3 methods using them are not (as they cannot be) subsequently used in Android.

(Strangely, this runs without problem in Android 5, but not in my devices under earlier versions)

**Comment by krisskross** [comment]
Thanks for reporting this. I have reverted the commit.
