### ISSUE TITLE
liblmdbjni.so: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found 

### ISSUE THREAD

**Issue by Neiko2002** [deephacks/lmdbjni#47]
I'm would like to run the library on a Debian 7 but have the problem with the old glibc 2.13. Are there any build-from-source instructions?

**Comment by krisskross** [comment]
```sudo apt-get install build-essential automake1.10 libtool```



I'll add a guide to the wiki later.

**Comment by Neiko2002** [comment]
Sounds great thank you.

**Comment by krisskross** [comment]
Btw, did you get it working with the instructions above?

**Comment by Neiko2002** [comment]
Yes it worked. I only got one error in the test suit:

testEnvInfo(org.fusesource.lmdbjni.EnvTest)  Time elapsed: 0.014 sec  <<< FAILURE!
java.lang.AssertionError: 
Expected: is <805568512>
     got: <939786240>

	at org.junit.Assert.assertThat(Assert.java:780)
	at org.junit.Assert.assertThat(Assert.java:738)
	at org.fusesource.lmdbjni.EnvTest.testEnvInfo(EnvTest.java:122)
