### ISSUE TITLE
EntryIterator improperly implements Iterator interface

### ISSUE THREAD

**Issue by devinrsmith** [deephacks/lmdbjni#52]
An iterators `hasNext` method should be idempotent. IE, the following two pieces of code should be functionally equivalent:

```
while (it.hasNext()) {
  it.next();
}
```

```
while (it.hasNext()) {
  if (!it.hasNext()) {
    throw new IllegalStateException();
  }
  it.next();
}
```

EntryIterator doesn't allow `hasNext` to be called multiple times, and I've run into some bugs that were traced down to this issue.

**Comment by krisskross** [comment]
I have updated the implementation to respect the Iterator contract along with some more tests. Do you mind reviewing it?

**Comment by devinrsmith** [comment]
Looks very reasonable on first glance. I see it's very similar to guava's AbstractIterator. Thanks.

**Comment by krisskross** [comment]
Yes, I took inspiration from AbstractIterator.  Thanks for reporting the issue and reviewing the fix.
