### ISSUE TITLE
setMapSize not working

### ISSUE THREAD

**Issue by ehamilto** [deephacks/lmdbjni#61]
Hi,

I have the following code,

			Env env = new Env();			
			env.open(storage_path,Constants.MAPASYNC|Constants.WRITEMAP);
			long mapsize = 100*1024*1024*1024;  //size 100 Gb
			env.setMapSize(mapsize);
			EnvInfo envinfo = env.info();
			System.out.println("Map size = "+envinfo.getMapSize());

I get in the standard output,

Map size = 1048576

as soon as operations start, I get

org.fusesource.lmdbjni.LMDBException: MDB_MAP_FULL: Environment mapsize limit reached
        at org.fusesource.lmdbjni.Util.checkErrorCode(Util.java:44)
        at org.fusesource.lmdbjni.Transaction.commit(Transaction.java:82)
        at org.fusesource.lmdbjni.Database.put(Database.java:384)
        at org.fusesource.lmdbjni.Database.put(Database.java:374)

I verify that the data file is indeed 1048576. Any idea on how to overcome this?

**Comment by krisskross** [comment]
This is how Java works. You're using an int to multiply then cast to long. The latest lmdbjni have a method `setMapSize(size, ByteUnit)`

**Comment by ehamilto** [comment]
Oh well, thanks for pointing it out. Now it works :-). I am closing this now.
