### ISSUE TITLE
Win32 supported

### ISSUE THREAD

**Issue by nikolakurtic** [deephacks/lmdbjni#62]
Hi, is WinXP 32bit supported?

Thanks!

**Comment by krisskross** [comment]
I'm not sure to what extent 32bit Windows is supported. You can try asking on OpenLDAP [mailing lists](http://www.openldap.org/lists/mm/listinfo/openldap-technical). 

We don't have a lmdbjni 32-bit build for Windows though, so you would need to build it yourself, sorry.
