### ISSUE TITLE
Stat.getEntries is missing in 0.4.6

### ISSUE THREAD

**Issue by stefanwouldgo** [deephacks/lmdbjni#65]
[error] /root/bge/src/main/scala/util/LmdbMap.scala:107: value getEntries is not a member of org.fusesource.lmdbjni.Stat
[error]     db.stat.getEntries.toInt

it works until 0.4.5, but breaks in 0.4.6

**Comment by krisskross** [comment]
Sorry this was changed in #50. Use the field `ms_entries` instead.

**Comment by stefanwouldgo** [comment]
Thank you.

**Comment by krisskross** [comment]
No problem. Sorry for the breakage.
