### ISSUE TITLE
assertion failed in 0.4.5

### ISSUE THREAD

**Issue by stefanwouldgo** [deephacks/lmdbjni#66]
src/mdb.c:5276: Assertion 'NUMKEYS(mp) > 1' failed in mdb_page_search_root()
Aborted

after millions of writes and reads.

**Comment by krisskross** [comment]
Never encountered this myself. What's your env? Test to reproduce?

**Comment by krisskross** [comment]
Probably regression in LMDB if not observed in earlier versions.

**Comment by stefanwouldgo** [comment]
I haven't tried reproducing, since this occured after about 12h of running [bitcoin graph explorer](https://github.com/bitcoinprivacy/Bitcoin-Graph-Explorer ) and I wanted to get our [project](https://bitcoinprivacy.net) running ASAP again. We get random LMDB errors (like MDB_BAD_VAL) from time to time and they are never reproducible. This one is new, though.

**Comment by krisskross** [comment]
There is an issue [ITS#8336](http://www.openldap.org/its/index.cgi/Software%20Bugs?id=8336;page=5#themesg) reported on LMDB 0.9.17 (fixed in LMDB 0.9.18) which sounds similar to your problem.  I would suggest you post your hardware spec, os and description of your problem to openldap-technical@openldap.org.

**Comment by krisskross** [comment]
LMDB 0.9.18 is in lmdbjni 0.4.6 btw.

**Comment by krisskross** [comment]
The fix of [ITS#8336](http://www.openldap.org/its/index.cgi/Software%20Bugs?id=8336;page=5#themesg) removes the assertion which should solve your problem. Howard's commit message for the fix seems to indicate that the assertion was harmless.

> Let "illegal" branch pages thru on the FreeDB - the condition
> is only temporary and will be fixed by the time rebalance finishes.

**Comment by krisskross** [comment]
Not sure about the random MDB_BAD_VAL errors though. Might be related if the rebalance wasn't finished?

**Comment by krisskross** [comment]
Did you have time to try 0.4.6?

**Comment by stefanwouldgo** [comment]
We've been running 0.4.6 since then. No problems so far :)

**Comment by krisskross** [comment]
Glad to hear. Let me know when you feel comfortable closing the issue.

**Comment by stefanwouldgo** [comment]
You're right, this should be resolved by the fix you mentioned. So I'm closing this issue. Thank you very much for your quick and thorough help, and for making LMDB available to the JVM ecosystem!

**Comment by krisskross** [comment]
Thanks! :-)
