### ISSUE TITLE
Fix for #49 is a problem for other users of hawtjni

### ISSUE THREAD

**Issue by krestenkrab** [deephacks/lmdbjni#67]
Fix for #49 is a problem for other users of hawtjni; I'm seeing the following

````
09:16:01 java.lang.RuntimeException: deduplicate: different file contents found in the following:
09:16:01 /var/lib/jenkins/.ivy2/cache/org.deephacks.lmdbjni/lmdbjni/jars/lmdbjni-0.4.6.jar:org/fusesource/hawtjni/runtime/Library.class
09:16:01 /var/lib/jenkins/.ivy2/cache/org.fusesource.leveldbjni/leveldbjni-all/bundles/leveldbjni-all-1.8.jar:org/fusesource/hawtjni/runtime/Library.class
````

**Comment by krisskross** [comment]
How did you make this work before hawtjni was shaded into lmdbjni? Either hawtjni dependency must have been excluded somehow?

**Comment by krisskross** [comment]
It seems 'sbt' is very picky about having multiple implementation on class path. Is it possible to suppress the error? You can always tweak your class path at runtime to make sure the right version is loaded first.

I need your input in order to take a decision if this is a problem or not.

**Comment by krisskross** [comment]
Closing from inactivity.
