### ISSUE TITLE
Compile and Build liblmdbjni and create liblmdbjni.so

### ISSUE THREAD

**Issue by aaditya14** [deephacks/lmdbjni#76]
Hi,
     I am  using lmdbjni and it's working fine in Windows. Now, i am trying to move this into Linux (redhat) and it's asking for ".so" file. I don't know ".so" file. Let me know how to make ".so" file, so that i can use lmdbjni in the linux environment.  Any help will be appreciated on this.  Any document available  for step by step process to build liblmdbjni.so.

**Comment by krisskross** [comment]
I haven't tried to build on redhat.  Can you explain the steps you tried with more detail?
