### ISSUE TITLE
malloc_error_break

### ISSUE THREAD

**Issue by devinrsmith** [deephacks/lmdbjni#80]
I'm able to run a simple program which seems to give the following error 100% of the time:

```
java(18017,0x70000021a000) malloc: *** error for object 0x7fb088722620: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
```

When using the IntelliJ debugger **and** breakpoint walking past the "error" `commit`, it produces a different error:

```
Exception in thread "main" org.fusesource.lmdbjni.LMDBException: MDB_MAP_FULL: Environment mapsize limit reached
	at org.fusesource.lmdbjni.Util.checkErrorCode(Util.java:44)
	at org.fusesource.lmdbjni.Transaction.commit(Transaction.java:82)
```

Taking this as a better hint, I updated my code to use a larger mapsize, and it seemed to resolve the issue. It seems like there may be an issues correctly reporting MDB_MAP_FULL?

**Comment by krisskross** [comment]
Can you provide the complete test case code?
