### ISSUE TITLE
Questions about transaction and read/write

### ISSUE THREAD

**Issue by lfoppiano** [deephacks/lmdbjni#81]
Hi,   
   I have few questions about LMDB, I apologize if they are obvious, but I'm not so familiar with key, value databases. I might have missed some point here. 

1. This example: 
```
byte[] key = bytes("London");
try (EntryIterator it = db.seek(tx, key)) {
  for (Entry next : it.iterable()) {
  }
}

try (EntryIterator it = db.seekBackward(tx, key))) {
  for (Entry next : it.iterable()) {
  }
}
```
What's the point of having try and a for to iterate to a `seek` that will return at maximum one value? Is this to avoid the `null check` on the value, in case the element is not present?

2. Write transactions: 
```
A cursor in a write-transaction can be closed before its transaction ends, and will otherwise be closed when its transaction ends. A cursor must not be used after its transaction is closed. Both these try blocks are unsafe and may SIGSEGV.
```

Does it means that I should not use the code as listed below? What would be the correct approach to this, to avoid SIGSEGV? 

Thanks
Luca

**Comment by krisskross** [comment]
1. The try/catch is just a safety measure that will rollback the transaction if not committed.
2. Yes.

**Comment by lfoppiano** [comment]
@krisskross thanks! I think you swapped the answers. 

Regarding number 2, (your answer number 1), why then in the documentation you wrote: `Both these try blocks are unsafe and may SIGSEGV`?

**Comment by krisskross** [comment]
Just to show that these two code blocks are unsafe, which might not be immediately obvious. These are not best practices, only a way to show the API.

**Comment by lfoppiano** [comment]
sorry, I really don't understand. 

What is not safe about these blocks? They will close/rollback the transaction eventually if something goes wrong which is a good thing. Why are you saying they are not safe then?  
If this are not best practices, what are the best practices in this case then?

**Comment by krisskross** [comment]
You are referring to these two blocks, right? They are unsafe because the transaction is closed before the cursor, which close when the try block ends.

```java
 try (Transaction tx = env.createWriteTransaction();
      Cursor cursor = db.openCursor(tx)) {
   ...
   tx.commit();
 }

 try (Transaction tx = env.createWriteTransaction();
      EntryIterator it = db.iterate(tx)) {
   ...
   tx.commit();
 }
```

**Comment by lfoppiano** [comment]
Ah yes. I see now! Thanks!

So I think a better approach would be something like this? Perhaps the `tx.commit()` should be insidet he cursor's `try-with-resources`? 

```
try (Transaction tx = env.createWriteTransaction()) {
      try (Cursor cursor = db.openCursor(tx)) {
           ...
      }
      tx.commit();
 }
```

**Comment by krisskross** [comment]
Yes, that works.
