### ISSUE TITLE
runtime exception :: /native/linux64/liblmdbjni.so: undefined symbol: pthread_mutexattr_setrobust

### ISSUE THREAD

**Issue by rishi3195** [deephacks/lmdbjni#85]
we are getting runtime exception when we are trying to load lmdbjni.so library in our application
/native/linux64/liblmdbjni.so: undefined symbol: pthread_mutexattr_setrobust.

What environment variable we have to set to access this library in our Application

**Comment by krisskross** [comment]
What OS are you running?

I found the following mail thread on the LMDB mailing list which might be related.

https://www.openldap.org/lists/openldap-technical/201510/msg00139.html
